joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

arm1_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot1_shoulder_pan_joint
    - robot1_shoulder_lift_joint
    - robot1_elbow_joint
    - robot1_wrist_1_joint
    - robot1_wrist_2_joint
    - robot1_wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    robot1_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    robot1_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    robot1_elbow_joint: {trajectory: 0.1, goal: 0.1}
    robot1_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    robot1_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    robot1_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  125
  action_monitor_rate: 10

hand1_controller:
  type: position_controllers/GripperActionController
  joint: robot1_gripper_finger1_joint
  action_monitor_rate: 20
  goal_tolerance: 0.002
  max_effort: 100
  stall_velocity_threshold: 0.001
  stall_timeout: 1.0

arm2_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot2_shoulder_pan_joint
    - robot2_shoulder_lift_joint
    - robot2_elbow_joint
    - robot2_wrist_1_joint
    - robot2_wrist_2_joint
    - robot2_wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    robot2_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    robot2_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    robot2_elbow_joint: {trajectory: 0.1, goal: 0.1}
    robot2_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    robot2_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    robot2_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  125
  action_monitor_rate: 10

hand2_controller:
  type: position_controllers/GripperActionController
  joint: robot2_gripper_finger1_joint
  action_monitor_rate: 20
  goal_tolerance: 0.002
  max_effort: 100
  stall_velocity_threshold: 0.001
  stall_timeout: 1.0