controller_list:
  - name: fake_arm1_controller
    joints:
      - robot1_shoulder_pan_joint
      - robot1_shoulder_lift_joint
      - robot1_elbow_joint
      - robot1_wrist_1_joint
      - robot1_wrist_2_joint
      - robot1_wrist_3_joint
  - name: fake_arm2_controller
    joints:
      - robot2_shoulder_pan_joint
      - robot2_shoulder_lift_joint
      - robot2_elbow_joint
      - robot2_wrist_1_joint
      - robot2_wrist_2_joint
      - robot2_wrist_3_joint
  - name: fake_hand1_controller
    joints:
      - robot1_gripper_finger1_joint
  - name: fake_hand2_controller
    joints:
      - robot2_gripper_finger1_joint
initial:  # Define initial robot poses.
  - group: arm1
    pose: arm1_zeros
  - group: arm2
    pose: arm2_zeros